refactor: encapsulate `Box` entity Phong values into a dedicated method
kinhosz/Appel pull request #136
Opened 2024-11-21 05:10 UTC by mateuseap

Closes #135

2024-11-23 16:17 UTC, kinhosz commented on src/entity/box.cpp
> +}
como discutido, remover isso do construtor.
E atualizar os testes

2024-11-25 18:02 UTC, kinhosz requested changes
ótimo. faltou atualizar a pasta `examples/*`

E após atualizar essa pasta, pega alguns exemplos, principalmente o que tem refração/reflexão e roda localmente comparando com o resultado que tinha antes para ter certeza que nada foi perdido.

2024-11-26 03:19 UTC, mateuseap commented
@kinhosz atualizei a pasta `example/*`!

Para garantir que tudo continua funcionando como esperado após o refactor, segui este processo:
1. Deletei os outputs já existentes.
2. Compilei e rodei cada `example` individualmente.
3. Comparei os novos outputs gerados com os arquivos atuais.

O resultado foi positivo: **não houve nenhuma alteração nos arquivos**. Todos os outputs "regerados" eram idênticos aos existentes.

Segue um registro:  
![image](https://github.com/user-attachments/assets/4c840cac-cfb4-4954-96c5-bc005b620960)

O que está presente no `example/view/*` eu também testei, tudo segue ok :+1:.

2024-11-26 10:53 UTC, kinhosz approved these changes
Super Nice \0/

2024-11-26 19:41 UTC, merged