Feat/box
kinhosz/Appel pull request #24
Opened 2023-08-01 04:13 UTC by mateuseap

---

title: Feat/box
labels: enhancement

---

## Related issues
- Object #7

## What I did
- Create `Box` header and source code files under `/geometry` folder and modify all the files related do `Color`.

@kinhosz
@mateuseap

2023-08-02 03:35 UTC, kinhosz requested changes

2023-08-02 03:35 UTC, kinhosz commented on include/geometry/box.h
> +struct Box {
eu sugiro ser uma classe. tô tentando usar a convenção:
* valores: color, rgb.., => struct
* coisas: class

2023-08-02 03:35 UTC, kinhosz commented on include/geometry/box.h
> +
![image](https://github.com/kinhosz/Appel/assets/39632709/62b3996b-8b35-4474-985f-33d623422f8a)

essas siglas talvez façam sentido agora, mas no futuro a gente confunda. o que tu acha de ao menos dentro da classe a gente colocar o nome completo? deixa sigla no chamando o construtor

2023-08-02 03:35 UTC, kinhosz commented on include/geometry/box.h
> +
esse color é interessante. o objeto em mais alto nível não tem uma cor única (ele pode ser um monte de triangulo, esfera...). o que tu acha da gente nao colocar cor aqui?

2023-08-02 03:35 UTC, kinhosz commented on include/graphic/color.h
> +    };
cara, eu gostei muito disso aqui. Eu sozinho não pensaria nisso, muito bom.

Minha única sugestão (se possível) colocar esse `union` fora de alguma forma, pode ser no mesmo arquivo do color. Só não sei se tem como, pra falar a verdade. Mas muito bom.

2023-08-02 03:35 UTC, kinhosz commented on include/graphic/color.h
> +    Color(double normRed, double normGreen, double normBlue, ColorRepresentation representation = NORMALIZED_RGB);
aqui eu tenho uma sugestão, pq ele pode passar o `representation = RGB` e mesmo assim colocar valores em `double`.

Cria um construtor só, coloca o `auto red, auto green, auto blue`. E faz um if. Se ele passar passar RGB, aí tu chama passa os valores como int. caso contrário, passa como double.

2023-08-04 05:12 UTC, mateuseap commented on include/geometry/box.h
> +struct Box {
Feito, agora o `Box` é uma classe.

2023-08-04 05:23 UTC, mateuseap commented on include/geometry/box.h
> +
A priori eu achei bem sugestivo utilizar apenas as siglas nos atributos, mas parando para pensar, não fica tão legível quando o contexto de onde essas siglas vem não tá fresco na mente. Atualizei colocando o nome completo nos atributos, ao invés de apenas as siglas:

```C++
double diffuseCoefficient; //double kd;
double specularCoefficient; //double ks;
double ambientCoefficient; //double ka;
double reflectionCoefficient; //double kr;
double transmissionCoefficient; //double kt;
double roughnessCoefficient //double roughness;
```

Apesar de ter ficado mais verboso, fica muito mais legível e fácil de entender o que é. No `constructor` eu mantive as siglas como tu também recomendou, faz sentido.

2023-08-04 05:24 UTC, mateuseap commented on include/geometry/box.h
> +
Removido :handshake:

2023-08-04 05:26 UTC, mateuseap commented on include/graphic/color.h
> +    };
Essa ideia daqui foi descontinuada, já que optamos por seguir o caminho de separar o **RGB padrão** (`Pixel`) do **RGB normalizado** (`Color`)

2023-08-04 05:28 UTC, mateuseap commented on include/graphic/color.h
> +    Color(double normRed, double normGreen, double normBlue, ColorRepresentation representation = NORMALIZED_RGB);
Mesma coisa aqui, com a implementação do `Pixel` para representar um **RGB padrão** (red, green e blue do tipo `int` e com valores entre [0, 255]) essa abordagem foi descontinuada.

2023-08-04 05:29 UTC, mateuseap commented on include/graphic/color.h
> +    Color(double normRed, double normGreen, double normBlue, ColorRepresentation representation = NORMALIZED_RGB);
Agora o `Color` representa apenas um `RGB normalizado`, os atributos red, green e blue são do tipo `double` e podem assumir valores entre [0, 1].

2023-08-04 14:53 UTC, mateuseap commented
@kinhosz o atributo `intensity` da classe `Light` voltou a ser do tipo `Color`, conforme a gente combinou.

2023-08-04 20:17 UTC, kinhosz approved these changes
LGTM

2023-08-05 00:41 UTC, merged