Feat/sphere
kinhosz/Appel pull request #61
Opened 2023-08-05 02:07 UTC by mateuseap

---
title: Feat/sphere
labels: enhancement
---

## Related issues
- Closes #8

## What I did
> Add `Sphere` header, source code and test files

## Properties
- Inherits `Box` class;
- `Point center`: point representing Shpere's center;
- `double radius`: Sphere's radius;
- `Color color`: normalized RGB color.

## Methods
- `getCenter`: returns Sphere's `Point center` attribute;
- `getRadius`: returns Sphere's `double radius` attribute;
- `getColor`: returns Sphere's `Color color` attribute;
- `setCenter`: sets Sphere's `Point center` attribute;
- `setRadius`: sets Sphere's `double radius` attribute;
- `setColor`: sets Sphere's `Color color` attribute.

@kinhosz
@mateuseap

2023-08-05 02:16 UTC, mateuseap commented
@kinhosz dá uma sacada nessa herança (`Sphere` herda `Box), vê se tá tudo ok por obséquio. Fora isso, achas que faz sentido adicionar getters/setters no `Box`? Senti falta disso quando tava criando os testes do `Sphere`, não tem como verificar se o `Box` foi criado corretamente.

2023-08-06 21:35 UTC, kinhosz approved these changes
LGTM

2023-08-06 21:37 UTC, kinhosz commented
> @kinhosz dá uma sacada nessa herança (`Sphere` herda `Box`), vê se tá tudo ok por obséquio. Fora isso, achas que faz sentido adicionar getters/setters no `Box`? Senti falta disso quando tava criando os testes do `Sphere`, não tem como verificar se o `Box` foi criado corretamente.

No momento não, a esperança é que a gente sempre tenha um box certo (se um box tiver errado, isso deveria ser reportado na class box). Mais na frente no intersect vamos precisar adicionar mais coisas no box, acho que por agora está tranquilo.

2023-08-06 22:37 UTC, kinhosz requested changes
Tu não achas que sphere faz mais sentido ser um "entity"?

2023-08-07 17:07 UTC, mateuseap commented
@kinhosz feito, agora o `Sphere` faz parte do módulo `entity`

2023-08-07 18:07 UTC, kinhosz approved these changes
LGTM

2023-08-07 18:17 UTC, merged