Feat/plane
kinhosz/Appel pull request #62
Opened 2023-08-05 03:21 UTC by mateuseap

---
title: Feat/plane
labels: enhancement

---

## Related issues
- Closes #9

## What I did
> Add `Plane` header, source code and test files.

## Properties
- Inherits `Box` class;
- `Point point`: point on the plane;
- `Vetor normalVector`: normal vector of the plane;
- `Color color`: normalized RGB color.

## Methods
- `getPoint`: returns `Point point` attribute;
- `getNormalVector`: returns `Vetor normalVector` attribute;
- `getColor`: returns `Color color` attribute;
- `setPoint`: sets `Point point` attribute;
- `setNormalVector`: sets `Vetor normalVector` attribute;
- `setColor`: sets `Color color` attribute.

## Additional notes
- `Plane` is part of `geometry` module.

@kinhosz
@mateuseap

2023-08-05 03:42 UTC, mateuseap commented
@kinhosz dá uma olhada aqui se a herança tá correta (`Plane` herda `Box`). Fora isso, assim como no já perguntei no PR #61: achas que faz sentido adicionar getters/setters no `Box`? Senti falta disso quando tava criando os testes do `Plane`, já que não tem como verificar se o `Box` foi criado corretamente.

Tô perguntando mais uma vez sobre essa questão de adicionar getters/setters no `Box` pra caso tu visualize esse PR antes do PR #61, tranquilo?! Se tu achar válido adicionar, vou deixar esse PR daqui (#62) on hold e adicionar esses getters/setters no `Box` dentro do PR #61, daí quando o PR #61 for mergeado, eu atualizo a branch desse PR daqui (#62) e faço as alterações necessárias.

2023-08-06 21:40 UTC, kinhosz approved these changes
LGTM

2023-08-06 21:41 UTC, kinhosz commented
> @kinhosz dá uma olhada aqui se a herança tá correta (`Plane` herda `Box`). Fora isso, assim como no já perguntei no PR #61: achas que faz sentido adicionar getters/setters no `Box`? Senti falta disso quando tava criando os testes do `Plane`, já que não tem como verificar se o `Box` foi criado corretamente.
> 
> Tô perguntando mais uma vez sobre essa questão de adicionar getters/setters no `Box` pra caso tu visualize esse PR antes do PR #61, tranquilo?! Se tu achar válido adicionar, vou deixar esse PR daqui (#62) on hold e adicionar esses getters/setters no `Box` dentro do PR #61, daí quando o PR #61 for mergeado, eu atualizo a branch desse PR daqui (#62) e faço as alterações necessárias.

respondido no PR #61

2023-08-06 22:38 UTC, kinhosz requested changes
embora plane seja geométrico, não faria sentido a gente tratar como uma entity?

2023-08-07 17:06 UTC, mateuseap commented
@kinhosz feito, agora o `Plane` faz parte do módulo `entity`

2023-08-07 18:08 UTC, kinhosz approved these changes
LGTM

2023-08-07 18:17 UTC, merged